### ISSUE TITLE
Gtest failure when running cmake .. inside build folder 

### ISSUE THREAD

**Issue by suab321321** [jaegertracing/jaeger-client-cpp#211] opened 2020-02-26 18:36 UTC
@yurishkuro the error is still there when I run `cmake ..` from build it shows me this output.
![Screenshot from 2020-02-26 23-51-21](https://user-images.githubusercontent.com/52123334/75374802-ed03ca80-58f2-11ea-92a4-7fd1017252d4.png)

the error is in the Gtest packages, so I tried to run this package individually, I went inside the directory `/.hunter/_Base/d45d77d/de38925/3b7ee27/Build/GTest` and did `cmake --build Build/` and this is the output I m getting

![Screenshot from 2020-02-26 23-56-00](https://user-images.githubusercontent.com/52123334/75375159-8f23b280-58f3-11ea-88b6-a4a8cd3b2246.png)

now I dont understand how to fix this.

OS - ubuntu 18.04
gcc - 9.2.1
g++ -9.2.1
branch - master

_Originally posted by @suab321321 in https://github.com/jaegertracing/jaeger-client-cpp/pull/209#issuecomment-591571949_

**Comment by suab321321** [comment] 2020-02-26 19:03
One fix is that you should remove the Gtest packages from `CMakeList.txt` in the root folder.
For time being this can used.

**Comment by mdouaihy** [comment] 2020-02-26 21:37
Hello @suab321321, we didnt build the library with the latest g++. GTest might not be compatible with that latest version. Did you try to check with Gtest devs?

**Comment by suab321321** [comment] 2020-02-27 03:49
@mdouaihy yes I think the issue is due to latest versions here is an issue with version problem https://github.com/google/googletest/issues/2721

**Comment by mdouaihy** [comment] 2020-02-27 18:38
Indeed. The problem is that we cant use the latest version of GTest now. The GTest library downloaded and built by Hunter does not contains the rpath. This should be figured out so that we can move to the latest version.

**Comment by suab321321** [comment] 2020-02-27 19:59
@mdouaihy one more thing is `thrift` not included in hunter, because I am unable to compile header `jaegertracing/Tracer.h` failing due to `thrift/stdcxx.h` not found.

**Comment by ideepika** [comment] 2020-03-12 15:24
for a workaround, if it is not necessary, you can turn off Gtests using `-DBUILD_TESTING=OFF`

**Comment by Namburger** [comment] 2021-01-11 14:24
Has there been a fix for this?

**Closed** 2022-01-10 19:41 UTC
